### PR TITLE
Build BEM styles by default

### PR DESCRIPTION
**Pull request by JockeTF**
Slightly more difficult to forget this way!

### CODE REVIEW

**Comment by JockeTF** [comment]
--> @sebastianthulin 

Thoughts on this? It seems to build fine now!

**Comment by sebastianthulin** [comment]
Yeah. Shure. But we really want to separate them as mutch as possible. The bem styles are a replacement for the old frontend code. It may not be production ready at this stage.

**Comment by JockeTF** [comment]
Aight!

**Comment by JockeTF** [comment]
This is now outdated. I may look into this again later.

**Pull request closed without merging**
